### ISSUE TITLE
Getting Internal Server Error on Veteran Verification - Disability Rating API & Service History API but not Status API

### ISSUE THREAD

**Issue by ccarollo** [department-of-veterans-affairs/vets-api-clients#293]
Getting 500 Internal Server error for two of three APIs that come from this endpoint... 

https://sandbox-api.va.gov/services/veteran_verification/v0

Here is an example of the token request response

```
{
  access_token: 'eyJraWQiOiJKemlmT01QdlhaaVRsSXRvcUZVakp3YUNMRjlBaGxxOGZPemhkMjFrY2FBIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmU3d0I5Vm1xaDJVeG8xNVp0R2hSR2poQXJjWkhRejg2UElkc3AwYl9MdGcub2FyeXcwMHZoR2Jad1dZRTIycDYiLCJpc3MiOiJodHRwczovL2RlcHR2YS1ldmFsLm9rdGEuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTYyOTI0MTEzOCwiZXhwIjoxNjI5MjQ0NzM4LCJjaWQiOiIwb2FicHBweG93SVdaczZ5azJwNyIsInVpZCI6IjAwdTN6NWU2YXM2dEV3WFd4MnA3Iiwic2NwIjpbImRpc2FiaWxpdHlfcmF0aW5nLnJlYWQiLCJvZmZsaW5lX2FjY2VzcyIsIm9wZW5pZCIsImVtYWlsIiwidmV0ZXJhbl9zdGF0dXMucmVhZCIsInByb2ZpbGUiLCJzZXJ2aWNlX2hpc3RvcnkucmVhZCJdLCJzdWIiOiJiMjQzNDZhNzg4YzA0ZGZlYTUwNDhkNDRhZDA3MTE4MSJ9.cNatzaf2C2twVDJpGQlwmN4mzzoRMOPkywShXOKHvXD2L_CQ0jh-Oisb1EJvoIif5hPRX80OzbdChgEPlDKRLtk_i_EeCrTs32_hPbBwQfhjH-D4OIpRBn2k_tcm3f3-nVv1tUO3oUfga3hTVNbY1ngwen0XQJo9U5tScNvF7a4PUiKJUhuqLZlFVsfC_v3fxQXC7kg4X4XZ5mb1fwHCJvl-DrF5evfWZTX_BqeSyW_UKToCS9FgVjnoyZaIqxXS1WhNA5rhN2-fXSJNyHXdsdKJaqlzG3dR360goQvVusi9GUWMsC9iP4Lecf-sOXcioOubLpIOk1pBgxkMIw23Gg',
  id_token: 'eyJraWQiOiJKemlmT01QdlhaaVRsSXRvcUZVakp3YUNMRjlBaGxxOGZPemhkMjFrY2FBIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIwMHUzejVlNmFzNnRFd1hXeDJwNyIsIm5hbWUiOiJUQU1BUkEgRUxMSVMiLCJlbWFpbCI6InZhLmFwaS51c2VyK2lkbWUuMDAxQGdtYWlsLmNvbSIsInZlciI6MSwiaXNzIjoiaHR0cHM6Ly9kZXB0dmEtZXZhbC5va3RhLmNvbS9vYXV0aDIvZGVmYXVsdCIsImF1ZCI6IjBvYWJwcHB4b3dJV1pzNnlrMnA3IiwiaWF0IjoxNjI5MjQxMTM4LCJleHAiOjE2MjkyNDQ3MzgsImp0aSI6IklELlpTMWVPaXhrY04wOEpFRjhFTWVhenpEWGhIZ3dGUldHa1NNZS1nUEpoYkUiLCJhbXIiOlsicHdkIl0sImlkcCI6IjBvYTU5c3Foc2dPSTh6b0FCMnA3IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYjI0MzQ2YTc4OGMwNGRmZWE1MDQ4ZDQ0YWQwNzExODEiLCJhdXRoX3RpbWUiOjE2MjkyNDExMzUsImF0X2hhc2giOiJWN3hjdklEU2RzTkJpazdMd083djRBIn0.e-ITyUYeB2ogpnvpvoIHCPjvpDLVv-OxycVQJWUHsnVXCrMPRB6K3jgq0rVp4Pt6qWYXNbX62vjgmfHD4rCfJiDmbBAA4N0ofdBSvRTbGbvK_KHEj8KMKsfi56tth_dM4twXyOL0QmInqUzHYEE4DEqpK_Y-43LPxsuvqYM9L_nOHNUNv8YL_MBQtYw1Nl3sCc0qKHIi2hn9iRJAJhOcK6NG7J33P_avD8RLYjMWhKUutjweSYLO3TdZUw5sTU7Og341rZuPUh3Wb8USwBMFr-HUIUXeAAPICb-Sfot22QHWhYEbyYYDOUypj7EMKMVxSaohTfp9ihZRJ-9dewHATg',
  refresh_token: '1ejC06ITuMb-vegPQNdOs28AJyigFzrhKoc3z8G72dE',
  token_type: 'Bearer',
  scope: 'disability_rating.read offline_access openid email veteran_status.read profile service_history.read',
  expires_in: 3600,
  state: '3563_893f_2e3b_b789_3dfe_1474_be4c_f790_c5ea_75c9_7452'
}
```

Here is the error that I am receiving for the Service History API

```
{
    "message": "Request failed with status code 500",
    "name": "Error",
    "stack": "Error: Request failed with status code 500\n    at createError (/Users/christian/Documents/api.worthright.com/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/christian/Documents/api.worthright.com/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/christian/Documents/api.worthright.com/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (node:events:390:22)\n    at IncomingMessage.EventEmitter.emit (node:domain:470:12)\n    at endReadableNT (node:internal/streams/readable:1307:12)\n    at processTicksAndRejections (node:internal/process/task_queues:81:21)",
    "config": {
        "url": "https://sandbox-api.va.gov/services/veteran_verification/v0/service_history",
        "method": "get",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Authorization": "Bearer eyJraWQiOiJKemlmT01QdlhaaVRsSXRvcUZVakp3YUNMRjlBaGxxOGZPemhkMjFrY2FBIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULmU3d0I5Vm1xaDJVeG8xNVp0R2hSR2poQXJjWkhRejg2UElkc3AwYl9MdGcub2FyeXcwMHZoR2Jad1dZRTIycDYiLCJpc3MiOiJodHRwczovL2RlcHR2YS1ldmFsLm9rdGEuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTYyOTI0MTEzOCwiZXhwIjoxNjI5MjQ0NzM4LCJjaWQiOiIwb2FicHBweG93SVdaczZ5azJwNyIsInVpZCI6IjAwdTN6NWU2YXM2dEV3WFd4MnA3Iiwic2NwIjpbImRpc2FiaWxpdHlfcmF0aW5nLnJlYWQiLCJvZmZsaW5lX2FjY2VzcyIsIm9wZW5pZCIsImVtYWlsIiwidmV0ZXJhbl9zdGF0dXMucmVhZCIsInByb2ZpbGUiLCJzZXJ2aWNlX2hpc3RvcnkucmVhZCJdLCJzdWIiOiJiMjQzNDZhNzg4YzA0ZGZlYTUwNDhkNDRhZDA3MTE4MSJ9.cNatzaf2C2twVDJpGQlwmN4mzzoRMOPkywShXOKHvXD2L_CQ0jh-Oisb1EJvoIif5hPRX80OzbdChgEPlDKRLtk_i_EeCrTs32_hPbBwQfhjH-D4OIpRBn2k_tcm3f3-nVv1tUO3oUfga3hTVNbY1ngwen0XQJo9U5tScNvF7a4PUiKJUhuqLZlFVsfC_v3fxQXC7kg4X4XZ5mb1fwHCJvl-DrF5evfWZTX_BqeSyW_UKToCS9FgVjnoyZaIqxXS1WhNA5rhN2-fXSJNyHXdsdKJaqlzG3dR360goQvVusi9GUWMsC9iP4Lecf-sOXcioOubLpIOk1pBgxkMIw23Gg",
            "User-Agent": "axios/0.21.1"
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1
    }
}
```

I am able to use the same token with the Status API and I am able to use the same token with Postman for all 3 APIs.

This is preventing us from completing our development sprint and launching our application.

Please advise, thank you.

**Comment by ryanlink** [comment]
Hi @ccarollo - can you please advise us of the exact HTTP request you are making that results in this 500 error response?

**Comment by ccarollo** [comment]
I am trying to request the following via node with the axios library.

https://sandbox-api.va.gov/services/veteran_verification/v0/status
https://sandbox-api.va.gov/services/veteran_verification/v0/service_history
https://sandbox-api.va.gov/services/veteran_verification/v0/disability_rating

The status API works but the other two do not.  I am able to access the other two APIs by using the node_fetch library.
I can confirm that the access_token is the same and correct substituted in all cases.

const REACT_APP_VA_SERVICE_AUTHORITY =
  "https://sandbox-api.va.gov/services/veteran_verification/v0";

1. Here is the status request signature that works...

const url = `${REACT_APP_VA_SERVICE_AUTHORITY}/status`;
axios
    .get(url, { headers: { Authorization: `Bearer ${access_token}` } })

2a. Here is the service_history request signature that does not work...

const url = `${REACT_APP_VA_SERVICE_AUTHORITY}/service_history`;
axios
    .get(url, { headers: { Authorization: `Bearer ${access_token}` } })

2b. Here is the service_history request signature that does work...

const url = `${REACT_APP_VA_SERVICE_AUTHORITY}/service_history`;
const results = await fetch(url, {
      method: "GET",
      headers: { Authorization: `Bearer ${access_token}` }
});

3a. Here is the disability_rating request signature that doesn't work...

const url = `${REACT_APP_VA_SERVICE_AUTHORITY}/disability_rating`;
axios
    .get(url, { headers: { Authorization: `Bearer ${access_token}` } })

3b. Here is the disability_rating request signature that does work...

const url = `${REACT_APP_VA_SERVICE_AUTHORITY}/disability_rating`;
const results = await fetch(url, {
      method: "GET",
      headers: { Authorization: `Bearer ${access_token}` }
});

Let me know if you need anything else.  

Thank you.

**Comment by lukemarkwordtlibertyits** [comment]
I am looking into this.

**Comment by lukemarkwordtlibertyits** [comment]
Hey @ccarollo it appears that axios does not specify a default accepted content type, so our apis do not know which format to return. Try this

```
const url = `${REACT_APP_VA_SERVICE_AUTHORITY}/disability_rating`;
axios
    .get(url, { headers: { Authorization: `Bearer ${access_token}`, Accept: 'application/json' } })
```

**Comment by dbrown-va** [comment]
Veteran Verification V0 is deprecated, closing this is issue.
