### ISSUE TITLE
State is missing from response

### ISSUE THREAD

**Issue by rhasan516** [department-of-veterans-affairs/vets-api-clients#34]
While trying to run the sample app, I am getting this error when I go to auth page (http://localhost:8080/auth)

Error: state missing from the response
    at Client.authorizationCallback (/va-oauth/node_modules/openid-client/lib/client.js:367:29)
    at OpenIDConnectStrategy.authenticate (/va-oauth/node_modules/openid-client/lib/passport_strategy.js:144:27)
    at attempt (/va-oauth/node_modules/passport/lib/middleware/authenticate.js:361:16)
    at authenticate (va-oauth/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/va-oauth/node_modules/express/lib/router/layer.js:95:5)
    at next (/va-oauth/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/va-oauth/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/va-oauth/node_modules/express/lib/router/layer.js:95:5)
    at /va-oauth/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/va-oauth/node_modules/express/lib/router/index.js:335:12)

I am new to this. I tried adding state along with client id and client secret, but still getting same error.

**Comment by rhasan516** [comment]
Tried both "token" (implicit flow) and "code" (Authorization code flow) using https://oauthdebugger.com/ but couldn't make it work.

My client id (which I received today): 0oa3cvphk1Mc7S2wr2p7

Please help.

**Comment by rhasan516** [comment]
Keep getting "The specified client is not valid". 

error=invalid_client
error_description=The+specified+client+is+not+valid

**Comment by rhasan516** [comment]
Its due to redirect uri mismatch. Now fixed.

**Comment by rufataliy** [comment]
Hey can you provide more info how you fixed it?
